Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission8.Models;


namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission8.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        public IMission7Repository repo { get; set; }
        public CategoriesViewComponent (IMission7Repository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card card-outline-primary m-1">
    <div class="card-header bg-faded p-2">
        @*Header Information*@
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    @*Remaining Information*@
<div class="card-body p-2">
    <div class="card-text p-1 col-6"><b>Author: </b>@Model.Author</div>
    <div class="card-text p-1 col-6"><b>Publisher: </b>@Model.Publisher</div>
    <div class="card-text p-1 col-6"><b>ISBN: </b>@Model.Isbn</div>
    <div class="card-text p-1 col-6"><b>Classification: </b>@Model.Classification</div>
    <div class="card-text p-1 col-6"><b>Category: </b>@Model.Category</div>
    <div class="card-text p-1 col-6"><b># of Pages: </b>@Model.PageCount</div>

    <form method="post" asp-page="/Buy">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Buy</button>
        </span>
    </form>
</div>

    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    @*Bringing in bootstrap, allowing for title and headers to be set in the controller*@
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">@ViewBag.Header</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    <br />
    <footer class="text-center">&copy;Thomas Lund 2022 <br /> IS 413 - Hilton</footer>
</body>
</html>